---
title: "Intro-to-R-Basics-Notes"
output:
  html_document:
     ############################# MathJax #############################
    mathjax: local
    self_contained: false
    ############################# MathJax #############################
    theme: dark
    highlight: breezedark
date: '2022-05-27'
--- 
<hr>
This document is the first of my `R`{.bash}-markdown files. This document contains code
and $\LaTeX$. To use the $\LaTeX$ syntax, use the following in `R`{.bash}-markdown.
```r
output:
  html_document:
    mathjax: local
    self_contained: false
```
## Arithmetic in R
Arithmetic in `R`{.bash} is quite simple. You can run it in the Console or run it line by line in the source file.
R supports $+,-,/,\cdot,$ and even modular arithmetic. Below are some examples.
```r
1+2 #Addition.
5-2 #Subtraction.
5*2 #Multiplication.
5/2 #Division.
5 %% 2 #Modular Arthimetic.
(5*2) + (5-3) #Order of operations.
```
## Variables
When it comes to variables in R there is a different assignment operator. This is the arrow operator `<-`{.r}
Below is how to use this operator on assigning `var`{.bash} the value `5`{.bash}.
```r
var <- 5 #5 is now stored as the variable "var."
```
The naming convention in R is variables are either camel case, or the space between words is represented as a `.`{.bash}
```r
bank.account <- 20 #"period" notation.
bankAccount <-872 #camel case.
```
## Basic Data Types
In R we have a variety of data types like `numberic, logical, character`{.bash}, etc. We can find out what variables data type is by calling a function called `class()`{.r}
```r
var <- 100
trueVar <- TRUE
falseVar <- FALSE
myName <- "Michael Dick"
class(var) #outputs: numeric
class(trueVar) #outputs: logical
class(falseVar) #outputs: logical
class(myName) #outputs: character
```
## Vector Basics
Vectors in R are 1-D arrays. The unique thing about these vectors is that they can act as a dictionary in Python. To initialize a vector in R we use the syntax: `vec <- c(10, 20 ,30)`{.r} where `c`{.bash} is a a function that combines all of these variables to be a part of this array. Now we can associate meaning to certain variable types. Look at the following:
```r
days <- c("Mon", "Tues", "Weds", "Thurs", "Fri", "Sat", "Sun") #Array of characters.
temps <- c(72, 55, 79, 60, 80, 70, 69) #Array of numerics.
names(temps) <- days #names assigns each item in temps a name from days
temps
```
`temps`{.bash} will display the following:
```r
 Mon  Tues  Weds Thurs   Fri   Sat   Sun 
   72    55    79    60    80    70    69 
```

## Vector Indexing and Slicing
With R it is VERY IMPORTANT to remember that indexing in R starts at `1`{.bash} rather than `0`{.bash}. There is a few unique things we can perform on vectors. Let's look at sample code:
```r
v1 <- c(100,200,300)
v2 <- c(a,b,c) 
v1[1] #Returns 100
temps[5] #Returns  Fri 
#                   80 
temps[2:4] #Splicing
#Returns: Tues  Weds Thurs 
#           55    79    60 
temps[c(1,7)] #Grab index 1 and index 7
temps["Mon"] #Returns the number assoicated with "Mon"
temps[c("Tues", "Fri")]
#Filter out values less than 2
vnum <- c(1,2,3,4)
vchar <- c('a', 'b', 'c', 'd')
names(vnum) <- vchar
vnum[vnum > 2] #Returns 3 and 4
vnum > 2
###################################
myFilter <- vnum > 2
vnum[myFilter]
###################################
```
For the `#`{.R} section of this code block you see we assign an array of logical operations. We can call this `myFiler`{.bash}. `myFilter`{.bash} will contain `{FALSE, FALSE, TRUE, TRUE}`{.R} and when we run `vnum[myFiler]`{.R} and this will return all the numbers that are greater than 2. It produces the result: 
```.code
c d 
3 4 
```
## Getting Help in R
To get help in R with variable names, functions, etc, you can easily do this in two ways.
<br>
<br>
1. Using `help()`{.R}, in the parthensis you would add what you need help one. For example, if you wanted help with vectors you would type `help("vector")`{.R} in the Console tab in RStudio.
<br>
<br>
2. Getting help by typing `?`{.bash} in front of what you want help with. Like in the last example, this is what you would use if you want to find more information on vectors `?.vectors`{.bash}

## Matricies in R

When building matricies we will use the built-in function `matrix()`{.bash}

### Syntax for `matrix()`{.bash}
```r
matrix(data = NA, nrow = 1, ncol = 1, byrow = FALSE, dimnames = NULL)
```
`data`{.bash} is what we are going to store in the matrix. By default it will store each entry as a row item. We can specify the number of rows by using `nrow`{.bash} when typing the matrix function. We can specify the number of columns we want by using `ncol`{.bash} when filling in the parameters of `matrix()`{.bash}. `byrom`{.bash} is a parameter in `matrix`{.bash} that is false by default, and this organizes the data fed into the matrix by row rather than column.

### Naming the Rows and the Columns

Let's work by example. We want to create a calendar with the days we are "On," and the days we are "Off."

```r
week1 <- c("On", "On", "Off", "On", "On")
week2 <- c("Off", "Off", "Off", "On", "On")
week3 <- c("On", "On", "On", "On", "On")
week4 <- c("Off", "Off", "On", "Off", "Off")
#Creating a 1D array of variables#
month <- c(week1, week2, week3, week4)
#Naming the matrix workMonth from the 1D array "month"#
workMonth <- matrix(month, ncol = 5, nrow = 4, byrow = TRUE)
#Naming columns from the days array.#
colnames(workMonth) <- days
workweek <- c('1','2','3','4')
#Naming the rows from the workweek vector.#
rownames(workMonth) <- workweek
workMonth
```
## Adding Rows and Columns to a Matrix

There is two new ideas here: `cbind`{.bash} and `rbind`{.bash}. For the syntax for each of these: `rbind(matrixName, rowName)`{.r}

```r
#Exam scores#
eecs183 <- c(93,100,39,55,29,42)
eecs203 <- c(100,23,37,56,98,78)
eecs280 <- c(100,23,94,25,82,45)
eecs281 <- c(81,54,73,65,55,47)
#Putting the class name into a vector#
grades <- c (eecs183, eecs203, eecs280, eecs281)
#Making a matrix to display grades as a table or 2D array#
gradesMatrix <- matrix(grades, nrow = 4, byrow = TRUE)
#Naming rows-start#
classes <- c("EECS183","EECS203","EECS280","EECS281")
rownames(gradesMatrix) <- classes
#Naming rows-end#
#Naming cols-start#
examNum <- c(1,2,3,4,5,6)
colnames(gradesMatrix) <- examNum
#Naming cols-end#

#Displays the sum for EACH column#
colSums(gradesMatrix)
rowSums(gradesMatrix)
rowMeans(gradesMatrix)

#Adding columns and rows to a matrix#
eecs370 <- c(78,88,21,55,91)
#Matrix name is to the right and name of row is the left.#
updatedGrades <- rbind(gradesMatrix, eecs370)
#Adding a column named average#
average <- rowMeans(updatedGrades)
updatedGrades <- cbind(updatedGrades, average)
updatedGrades

```
## Factor and Categorical Matrices
Using R you can give a vector a certain order. When it comes to the idea of, say, that hot is better than cold, how can we show this? Using a function called `factor`{.bash} we can assign this kind of order. Let's look at this example:
```r
animal <- c("dog", "cat", "dog", "cat", "cat")
#ID Number for dog and cat.#
idNum <- c(1,2,3,4,5)
factor(animal)
#Levels cat and dog are now assigned to animal vector.#
factorAnimal <- factor(animal)
#Nominal means there is no order. Ordinal means there is an order.

#Here is an order: cold < med < hot.
temps <- c("cold", "med", "hot", "hot", "hot", "cold", "med")
#We give factor the vector list, tell that this is ordered#
#, and now give the factor function the order that we want.#
factTemps <- factor(temps, ordered = TRUE, levels = c("cold", "med", "hot"))
factTemps
#Prints the number of times each word is present in the vector.#
summary(factTemps)

```



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

